### ISSUE TITLE
Parametrizar informações do Git

### ISSUE THREAD

**Issue by marcopollivier** [marcopollivier/scripts-devops#2]
hoje as informações de config do usuário do GIT estão fixas

**Comment by Hixian** [comment]
Dá uma lida sobre os 2 assuntos abaixo:

**Variables**

https://liquidat.wordpress.com/2016/01/26/howto-introduction-to-ansible-variables/


**ansible-vault**

https://www.digitalocean.com/community/tutorials/how-to-use-vault-to-protect-sensitive-ansible-data-on-ubuntu-16-04

https://serversforhackers.com/c/how-ansible-vault-works

**Comment by marcopollivier** [comment]
Passar as informacoes na hora de chamar o sh de instalação
